# Generated by Django 6.0 on 2026-01-21 16:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeUniversitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_annee', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Le format doit être YYYY-YYYY (ex: 2024-2025)', regex='^\\d{4}-\\d{4}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_filiere', models.CharField(max_length=30)),
                ('nom_filiere_fr', models.CharField(max_length=255)),
                ('nom_filiere_ar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StructureDiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pays_fr', models.CharField(max_length=150)),
                ('nom_pays_ar', models.CharField(max_length=150)),
                ('devise_nationale_fr', models.CharField(max_length=150)),
                ('devise_nationale_ar', models.CharField(max_length=150)),
                ('nom_ministere_fr', models.CharField(max_length=250)),
                ('nom_ministere_ar', models.CharField(max_length=250)),
                ('nom_groupe_fr', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_groupe_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_institut_fr', models.CharField(blank=True, max_length=250, null=True)),
                ('nom_institut_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('intitule_diplome_fr', models.CharField(blank=True, max_length=250, null=True)),
                ('intitule_diplome_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('signataire_1_nom_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('signataire_1_nom_ar', models.CharField(blank=True, max_length=150, null=True)),
                ('signataire_2_nom_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('signataire_2_nom_ar', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom_fr', models.CharField(max_length=50)),
                ('nom_prenom_ar', models.CharField(max_length=255)),
                ('matricule', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('nni', models.IntegerField(unique=True)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance_fr', models.CharField(max_length=100)),
                ('lieu_naissance_ar', models.CharField(max_length=100)),
                ('mention_fr', models.CharField(max_length=100)),
                ('mention_ar', models.CharField(max_length=100)),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='core.anneeuniversitaire')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_diplome', models.IntegerField()),
                ('type_diplome', models.CharField(max_length=100)),
                ('annee_obtention', models.IntegerField()),
                ('fichier_pdf', models.CharField(max_length=400)),
                ('hash_signature', models.CharField(max_length=64, unique=True)),
                ('verification_uuid', models.CharField(default='882abd669d7f43f5bfaf3a1f80ffc7cb', max_length=32, unique=True)),
                ('date_televersement', models.DateTimeField(auto_now_add=True)),
                ('est_annule', models.BooleanField(default=False)),
                ('annule_a', models.DateTimeField(blank=True, null=True)),
                ('raison_annulation', models.TextField(blank=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Diplômes', to='core.etudiant')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec')], max_length=20)),
                ('diplome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='core.diplome')),
            ],
        ),
    ]
