# Generated by Django 6.0 on 2026-01-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='verification_uuid',
            field=models.CharField(default='b00066feda1044e599b9e127ea19ee62', max_length=32, unique=True),
        ),
    ]
