# Generated by Django 6.0 on 2026-01-21 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_diplome_verification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Diplomes', to='core.etudiant'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='verification_uuid',
            field=models.CharField(default='be43733653f844c590c2e0530ff440f6', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nni',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
