# Generated by Django 6.0 on 2026-01-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_diplome_etudiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurediplome',
            name='image_iss',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='image_poly',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diplome',
            name='verification_uuid',
            field=models.CharField(default='95a0d3a319494b54a88b57066a843d62', max_length=32, unique=True),
        ),
    ]
