# Generated by Django 6.0 on 2026-01-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_structurediplome_image_iss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structurediplome',
            old_name='nom_ministere_ar',
            new_name='diplome_titre_ar',
        ),
        migrations.RenameField(
            model_name='structurediplome',
            old_name='nom_ministere_fr',
            new_name='diplome_titre_fr',
        ),
        migrations.RenameField(
            model_name='structurediplome',
            old_name='devise_nationale_ar',
            new_name='pays_ar',
        ),
        migrations.RenameField(
            model_name='structurediplome',
            old_name='devise_nationale_fr',
            new_name='pays_fr',
        ),
        migrations.RenameField(
            model_name='structurediplome',
            old_name='nom_pays_ar',
            new_name='signataire_1_ar',
        ),
        migrations.RenameField(
            model_name='structurediplome',
            old_name='nom_pays_fr',
            new_name='signataire_1_fr',
        ),
        migrations.RenameField(
            model_name='structurediplome',
            old_name='signataire_1_nom_ar',
            new_name='signataire_2_ar',
        ),
        migrations.RenameField(
            model_name='structurediplome',
            old_name='signataire_1_nom_fr',
            new_name='signataire_2_fr',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='image_iss',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='image_poly',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='intitule_diplome_ar',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='intitule_diplome_fr',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='nom_groupe_ar',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='nom_groupe_fr',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='nom_institut_ar',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='nom_institut_fr',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='signataire_2_nom_ar',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='signataire_2_nom_fr',
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='image_border',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='image_logo',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='institut_ar',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='institut_fr',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='ministere_ar',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='ministere_fr',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='texte_principal_ar',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='texte_principal_fr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diplome',
            name='verification_uuid',
            field=models.CharField(default='705b7d5f50bd482a894737835d537879', max_length=32, unique=True),
        ),
    ]
