# Generated by Django 6.0 on 2026-01-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_nom_ministere_ar_structurediplome_diplome_titre_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structurediplome',
            old_name='image_logo',
            new_name='image_logo_left',
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='image_logo_right',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diplome',
            name='verification_uuid',
            field=models.CharField(default='43df112f285246929b8f4a9c5a92a73c', max_length=32, unique=True),
        ),
    ]
