# Generated by Django 6.0 on 2026-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_image_logo_structurediplome_image_logo_left_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structurediplome',
            old_name='pays_ar',
            new_name='signataire_droit_ar',
        ),
        migrations.RenameField(
            model_name='structurediplome',
            old_name='pays_fr',
            new_name='signataire_droit_fr',
        ),
        migrations.RenameField(
            model_name='structurediplome',
            old_name='signataire_1_ar',
            new_name='signataire_droit_nom',
        ),
        migrations.RenameField(
            model_name='structurediplome',
            old_name='signataire_1_fr',
            new_name='signataire_gauche_ar',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='signataire_2_ar',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='signataire_2_fr',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='texte_principal_ar',
        ),
        migrations.RemoveField(
            model_name='structurediplome',
            name='texte_principal_fr',
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='citations_juridiques_ar',
            field=models.TextField(default='', help_text='قائمة القوانين والمراسيم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='citations_juridiques_fr',
            field=models.TextField(default='', help_text='Liste des décrets et lois'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='date_pv_jury',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='date_verification',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='devise_ar',
            field=models.CharField(default='شرف-إخاء-عدل', max_length=150),
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='devise_fr',
            field=models.CharField(default='Honneur-Fraternité-Justice', max_length=150),
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='groupe_ar',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='groupe_fr',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='label_pv_jury_ar',
            field=models.CharField(default='وبناء على محضر لجنة الامتحانات الصادر بتاريخ', max_length=255),
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='label_pv_jury_fr',
            field=models.CharField(default='Vu le procès-verbal du jury des examens tenu en date du', max_length=255),
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='republique_ar',
            field=models.CharField(default='الجمهورية الإسلامية الموريتانية', max_length=150),
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='republique_fr',
            field=models.CharField(default='REPUBLIQUE ISLAMIQUE DE MAURITANIE', max_length=150),
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='signataire_gauche_fr',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structurediplome',
            name='signataire_gauche_nom',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diplome',
            name='verification_uuid',
            field=models.CharField(default='594cb7eecb99400ca13062de01ce36e6', max_length=32, unique=True),
        ),
    ]
