# Generated by Django 6.0 on 2026-02-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_pays_ar_structurediplome_signataire_droit_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='verification_uuid',
            field=models.CharField(default='2f276762e7604ec3a7046ec2144a4bad', max_length=32, unique=True),
        ),
        migrations.AddConstraint(
            model_name='diplome',
            constraint=models.UniqueConstraint(fields=('annee_obtention', 'numero_diplome'), name='unique_diplome_per_year'),
        ),
    ]
