# Generated by Django 6.0 on 2026-02-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_diplome_verification_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='verification_uuid',
            field=models.CharField(default='a2d3dbc09d61406f9fa950d273a8dc48', max_length=32, unique=True),
        ),
    ]
